management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      show-details: always


server:
  port: 8081
  servlet:
    context-path: /superapp/banneradministrator